### ISSUE TITLE
Module provisions Windows client images as azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by janegilring** [crayon/terraform-azurerm-vm#23]
When deploying a Windows client image such as Windows 10, the module in version 1.9 provisions azurerm_linux_virtual_machine.

Example image:

```
    source_image_reference = {
      publisher = "MicrosoftWindowsDesktop"
      offer     = "Windows-10"
      sku       = "20h2-evd" # This is the Windows 10 Enterprise Multi-Session image
      version   = "latest"
    }
```

**Comment by janegilring** [comment]
Suggestion: In locals.tf, change this
```
image_reference_os = var.source_image_reference.offer == "WindowsServer" ? "windows" : "linux"
```

to

```
image_reference_os = length(regexall("^Windows",var.source_image_reference.offer)) > 0 == true ? "windows" : "linux"
```

**Comment by roberthstrand** [comment]
Ended up with the following:
`image_reference_os = can(regex("(Windows)", var.source_image_reference.offer)) ? "windows" : "linux"`

Using can which returns true or false depending on if your checks pass and regex to find if the variable `source_image_reference.offer` contains _Windows_ or not, we now will make a new Windows VM as long as the offer has _Windows_ in it.

This is a huge improvement over just supporting Windows Servers, thanks for reporting and the suggestions 🎉

**Comment by janegilring** [comment]
This issue is also present when using the Office 365 image for Azure Virtual Desktop:
```
source_image_reference = {
    publisher = "microsoftwindowsdesktop"
    offer     = "office-365"
    sku       = "20h1-evd-o365pp-g2"
    version   = "latest"
  }
```

**Comment by roberthstrand** [comment]
We could change it so that it checks publisher instead, as both Windows Desktop and Server will have the word Windows in it. I'm adding the change to the next release, which should be out this week.

**Comment by janegilring** [comment]
Also, it would be nice if the regex check on "offer" is not case-sensitive.

Fails:
offer     = "windows-10"

Works:
offer     = "Windows-10"
